# Generated by Django 5.1.7 on 2025-03-13 12:17

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_photo',
            field=models.ImageField(default=builtins.print, upload_to='media'),
            preserve_default=False,
        ),
    ]
