# Generated by Django 5.1.7 on 2025-03-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_news_news_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
